### ISSUE TITLE
ValueError: Registry initialized -  ckan_2.9_support.

### ISSUE THREAD

**Issue by pribadihcr** [data-govt-nz/ckanext-dia_theme#43]
Hi I Got the following error when using ckan_2.9_support branh.

'''
ckan          |   File "/usr/local/lib/python3.8/dist-packages/fanstatic/registry.py", line 72, in __setitem__
ckan          |     raise ValueError('Registry initialized.')
ckan          | ValueError: Registry initialized.
'''

**Comment by markstuart** [comment]
Thanks, this is very much a work in progress branch but I'll take a look at this error when I get back to this.

**Comment by markstuart** [comment]
Hi @pribadihcr, I'm a little surprised that people outside of the data-govt-nz organization would use this theme... obviously it's open source, but it aims to make a base CKAN installation look exactly like [catalogue.data.govt.nz](https://catalogue.data.govt.nz).

Possibly you're using it as a base or example to work from?

Anyway, hopefully you are no longer seeing the error that you were before. The `ckan_2.9_support` branch has been merged to `master`.
